"use strict";
const D=window.HomeDomain, $=id=>document.getElementById(id), views=["login","executor","start","activity","manager","detail"];
let identity=null,active=null,all=[],offset=0,selectedDetail=null;
const creds={"executor-demo":{pass:"CleanDemo26!",roles:["Executor"]},"manager-demo":{pass:"ViewDemo26!",roles:["Manager"]}};
const now=()=>new Date().toISOString(),uuid=prefix=>prefix+"-"+crypto.randomUUID();
const pretty=iso=>new Date(iso).toLocaleString();
const status=(text,error=false)=>{$("feedback").textContent=text;$("feedback").className=error?"error":"positive";};
const database=new Promise((resolve,reject)=>{const request=indexedDB.open("cco-home-mvp-v1",1);request.onupgradeneeded=()=>request.result.createObjectStore("activities",{keyPath:"id"});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
async function allRecords(){const db=await database;return new Promise((ok,fail)=>{const t=db.transaction("activities","readonly"),r=t.objectStore("activities").getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error);});}
async function persist(item){const db=await database;return new Promise((ok,fail)=>{const t=db.transaction("activities","readwrite");t.objectStore("activities").put(item);t.oncomplete=ok;t.onerror=()=>fail(t.error||new Error("Device storage failed"));});}
async function refresh(){all=await allRecords();}
function show(view){if(view!=="login"&&!identity)return show("login");if(["executor","start","activity"].includes(view)&&!identity?.roles.includes("Executor"))return show("manager");if(["manager","detail"].includes(view)&&!identity?.roles.includes("Manager"))return show("executor");views.forEach(x=>$(x+"-view").classList.toggle("hidden",x!==view));$("top-nav").classList.toggle("hidden",!identity);window.scrollTo(0,0);}
function home(){if(!identity)return show("login");if(identity.roles.includes("Executor"))return executorHome();return managerHome();}
async function executorHome(){await refresh();const mine=all.filter(x=>x.executor===identity.name&&x.status==="in_progress").sort((a,b)=>b.startedAt.localeCompare(a.startedAt));const box=$("active-box");box.replaceChildren();if(mine.length){const p=document.createElement("p");p.textContent=mine.length+" unfinished activity(s)";box.append(p);for(const a of mine){const b=document.createElement("button");b.textContent="Continue "+D.rooms[a.roomId]+" · "+pretty(a.startedAt);b.onclick=()=>openActivity(a.id);box.append(b);}}else{box.textContent="No unfinished activities.";}show("executor");}
async function openActivity(id){await refresh();active=all.find(x=>x.id===id);if(!active)return status("Activity not found",true);$("activity-title").textContent=D.rooms[active.roomId];$("activity-meta").textContent=active.id+" · Started "+pretty(active.startedAt);$("activity-state").textContent=active.status.replace("_"," ");await renderPhotos();show("activity");}
function putText(id,text){$(id).textContent=text;}
async function renderPhotos(){if(!active)return;for(const stage of ["before","after"]){const el=$(stage+"-gallery");el.replaceChildren();const photos=active.photos.filter(x=>x.stage===stage);for(const item of photos){const card=document.createElement("div");card.className="photo";const img=document.createElement("img"),url=URL.createObjectURL(item.blob);img.src=url;img.alt=stage+" photo";img.onload=()=>URL.revokeObjectURL(url);const label=document.createElement("small");label.textContent=item.name;card.append(img,label);if(active.status==="in_progress"){const remove=document.createElement("button");remove.textContent="Remove";remove.className="danger";remove.onclick=async()=>{const old=active.photos;active.photos=old.filter(x=>x.id!==item.id);try{await persist(active);await renderPhotos();status("Photo removed from local draft.");}catch(e){active.photos=old;status("Could not save change: "+e.message,true);}};card.append(remove);}el.append(card);}}putText("photo-count",active.photos.filter(x=>x.stage==="before").length+" before · "+active.photos.filter(x=>x.stage==="after").length+" after (stored in this browser only)");$("finish").disabled=!D.canComplete(active);}
async function attach(stage,event){if(!active||active.status!=="in_progress")return;const files=[...event.target.files];event.target.value="";if(!files.length)return;const original=active.photos;const t=performance.now();const accepted=files.filter(file=>file.type.startsWith("image/")&&file.size<=12*1024*1024);if(accepted.length!==files.length)status("Some files were skipped (image files up to 12 MB only).",true);active.photos=[...original,...accepted.map(file=>({id:uuid("EV"),stage,name:file.name,mime:file.type,bytes:file.size,blob:file,addedAt:now()}))];try{await persist(active);await renderPhotos();putText("write-time","Local save: "+Math.round(performance.now()-t)+" ms · No Google Drive upload");status("Photo(s) added to local draft. Review or remove before completion.");}catch(e){active.photos=original;status("Photo could not be saved locally: "+e.message,true);}}
async function managerHome(){await refresh();const stats=$("stats");stats.replaceChildren();const data=D.summary(all);for(const room of data){const div=document.createElement("div");div.className="stat";const b=document.createElement("b");b.textContent=room.completed?"Completed":"Not recorded";b.style.fontSize="17px";const small=document.createElement("small");small.textContent=room.name+" · "+room.completed+" completed today";div.append(b,small);stats.append(div);}offset=0;await renderRegister();show("manager");}
async function renderRegister(){const days={today:1,week:7,month:30}[$("period").value]||1;const match=D.filter(all,days,$("filter-room").value);const list=$("register");list.replaceChildren();if(!match.length)list.textContent="No matching activities.";for(const row of match.slice(0,offset+20)){const div=document.createElement("div");div.className="activity";const strong=document.createElement("strong");strong.textContent=D.rooms[row.roomId]+" · "+row.status.replace("_"," ");const caption=document.createElement("div");caption.className="muted";caption.textContent=pretty(row.startedAt)+(row.completedAt?" · "+row.durationSeconds+" seconds":"");const button=document.createElement("button");button.textContent="View Details and Photos";button.onclick=()=>details(row.id);div.append(strong,caption,button);list.append(div);}$("load-more").classList.toggle("hidden",match.length<=offset+20);}
function drawDetail(stage,record){const el=$("detail-"+stage);el.replaceChildren();for(const p of record.photos.filter(x=>x.stage===stage)){const card=document.createElement("div");card.className="photo";const img=document.createElement("img"),url=URL.createObjectURL(p.blob);img.src=url;img.alt=stage+" photo";img.onload=()=>URL.revokeObjectURL(url);const info=document.createElement("small");info.textContent=p.name;card.append(img,info);el.append(card);}}
async function details(id){await refresh();selectedDetail=all.find(x=>x.id===id);if(!selectedDetail)return status("Activity not found",true);$("detail-heading").textContent=D.rooms[selectedDetail.roomId];$("detail-meta").textContent=selectedDetail.id+" · "+selectedDetail.status+" · Start: "+pretty(selectedDetail.startedAt)+(selectedDetail.completedAt?" · Completed: "+pretty(selectedDetail.completedAt)+" · Duration: "+selectedDetail.durationSeconds+" seconds":"");drawDetail("before",selectedDetail);drawDetail("after",selectedDetail);show("detail");}
$("sign-in").onclick=()=>{const name=$("username").value.trim(),pass=$("password").value,match=creds[name];if(!match||match.pass!==pass){status("Invalid preview credentials.",true);return;}identity={name,roles:match.roles};$("password").value="";status("Preview sign-in: "+identity.roles.join(", ")+". No server authentication.");home().catch(e=>status(e.message,true));};
$("logout").onclick=()=>{identity=null;active=null;show("login");status("Signed out of the preview.");};
$("go-home").onclick=()=>home().catch(e=>status(e.message,true));
$("new-activity").onclick=()=>show("start");
$("create").onclick=async()=>{const roomId=$("room").value;if(!D.rooms[roomId])return status("Select a room.",true);const t=performance.now();const activity={id:uuid("ACT"),definitionId:"DEF-CLEAN",roomId,executor:identity.name,notes:$("notes").value.trim(),startedAt:now(),completedAt:null,durationSeconds:null,status:"in_progress",photos:[]};try{await persist(activity);status("Local activity saved in "+Math.round(performance.now()-t)+" ms (not Google Sheets).");await openActivity(activity.id);}catch(e){status("Could not start activity: "+e.message,true);}};
for(const stage of ["before","after"])$(stage).addEventListener("change",e=>attach(stage,e).catch(err=>status(err.message,true)));
$("finish").onclick=async()=>{if(!D.canComplete(active))return status("At least one before and one after photograph is required.",true);$("finish").disabled=true;const t=performance.now(),completedAt=now();const updated={...active,status:"completed",completedAt,durationSeconds:D.seconds(active.startedAt,completedAt)};try{await persist(updated);active=updated;await renderPhotos();putText("write-time","Completed in local storage in "+Math.round(performance.now()-t)+" ms. Not uploaded to Sheets/Drive.");status("Completed in browser-only QA storage. Sign in as manager on this device to review.");}catch(e){$("finish").disabled=false;status("Completion failed: "+e.message,true);}};
$("refresh").onclick=()=>managerHome().catch(e=>status(e.message,true));
for(const key of ["period","filter-room"])$(key).onchange=()=>{offset=0;renderRegister();};
$("load-more").onclick=()=>{offset+=20;renderRegister();};
$("back-manager").onclick=()=>managerHome();
show("login");